# Add this to your Home Assistant configuration.yaml to enable detailed logging for Meridian Solar

logger:
  default: info
  logs:
    # Meridian Solar Integration Logging
    custom_components.meridian_solar: debug
    custom_components.meridian_solar.sensor: debug
    custom_components.meridian_solar.config_flow: debug
    
    # Home Assistant Core Sensor Logging (for debugging sensor issues)
    homeassistant.components.sensor: info
    homeassistant.helpers.update_coordinator: debug
    
    # HTTP and aiohttp logging (to see web requests)
    aiohttp.access: debug
    
# Optional: Enable file logging for persistent logs
# Uncomment and modify path as needed:
#
# logger:
#   default: info
#   logs:
#     custom_components.meridian_solar: debug
#   handlers:
#     file:
#       class: logging.handlers.RotatingFileHandler
#       level: DEBUG
#       filename: /config/meridian_solar.log
#       maxBytes: 10485760  # 10MB
#       backupCount: 3
#       formatter: homeassistant
#   loggers:
#     custom_components.meridian_solar:
#       handlers: [file]
#       level: DEBUG
#       propagate: false

# After adding this config:
# 1. Restart Home Assistant
# 2. Go to Settings → System → Logs
# 3. Look for "custom_components.meridian_solar" entries
# 4. You can also set log level to "Debug" in the UI
